---
title: "p8105_hw2_kw2873"
author: "Keyi Wang"
date: "9/25/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)

```

```{r}
Wheel_data = 
   readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",sheet = 1) %>%
   janitor::clean_names() %>%
   drop_na(dumpster) %>%
   mutate(
   sports_balls = as.integer(sports_balls) 
   )

```


```{r}
### clean and modify data set for precipitation in 2017
preci_2017_data =
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",
                     sheet = 4,skip = 1) %>%
  janitor::clean_names()  %>%
  mutate( year = 2017,
          total_precipitation = total
          ) %>%
drop_na(total_precipitation) 

### clean and modify dataset for precipitation in 2018
preci_2018_data =
readxl::read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx",sheet = 3, 
                   skip = 1) %>%
  janitor::clean_names() %>%
  mutate( year = 2018,
          total_precipitation = total
          ) %>%
  drop_na(total_precipitation)  

### combiing dataset for precipitation in 2017 and 2018 
preci_17_18_data =
   bind_rows(preci_2017_data, preci_2018_data) %>%
   mutate(month = month.name[month]
   )
```

### problem 2
```{r}
### manipulation pols monts data
pols_months_data = 
  read_csv("./data/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(col = mon, into = c("year","month","day")) %>%
 pivot_longer(
  starts_with("prez"),
  names_to = "president",
   names_prefix = "prez_",
   values_to = "value") %>%
   filter(!(value == "0")) %>%   
   select(year, month, everything(), -value, -day) %>%
   mutate(year = as.integer(year))


### manipulation of snp.csv----problem with year 
snp_data = 
  read_csv("./data/snp.csv") %>%
  janitor::clean_names() %>%
  separate(col = date, into = c("day","month","year")) %>%
  mutate(close = as.integer(close)) %>%
  select(year, month, everything(),-day)  %>%
  mutate(year = as.integer(year))


### manipulation of unemployment.csv
unemployment_data = 
  read_csv("./data/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
     cols = jan:dec,
     names_to = "month",
     values_to = "umemployment value"
     ) %>%
 mutate(year = as.integer(year))

### joining dataset
merged_data = 
  left_join(pols_months_data, snp_data, by = c("year","month")) %>% 
  left_join(., unemployment_data, by = c("year","month"))
```
### problem 3
```{r}
baby_names_data = 
  read_csv("./data/Popular_Baby_Names.csv", col_types = "icccii") %>% 
  janitor::clean_names() %>%
  mutate_all(~replace(., ethnicity == "ASIAN AND PACI", 
                      "ASIAN AND PACIFIC ISLANDER")) %>% 
  mutate_all(~replace(., ethnicity == "BLACK NON HISP", 
                      "BLACK NON HISPANIC")) %>% 
  mutate_all(~replace(., ethnicity == "WHITE NON HISP", 
                      "WHITE NON HISPANIC")) %>% 
 distinct() ### remove replicate row

Olivia_female =
  filter(baby_names_data, childs_first_name == "Olivia", gender == "FEMALE") %>% 
  pivot_wider(
    id_cols = c("ethnicity", "year_of_birth"),
    names_from = "year_of_birth",
    values_from = "rank"
  )

Popular_name_male = 
  filter(baby_names_data, rank == 1, gender == "MALE") %>% 
  pivot_wider(
    # find unique identifer
    id_cols = c("ethnicity", "year_of_birth"),
    # put years into column
    names_from = "year_of_birth",
    # put names into table cells
    values_from = "childs_first_name"
  )

white_non_hisp_2016 = 
  filter(baby_names_data, year_of_birth == 2016, gender == "MALE", ethnicity == "WHITE NON HISPANIC") %>% 
  mutate(count = as.integer(count), rank = as.integer(rank))

white_non_hisp_2016

ggplot(data = white_non_hisp_2016) + geom_point(aes(x = rank, y = count))


```


